---
# =============================================================================
# Ansible Role: Alloy - Tasks: Prerequisites
# =============================================================================
# Dispatcher for OS-specific package repository setup per Red Hat CoP.
# =============================================================================

- name: Alloy | prerequisites | Run Debian/Ubuntu prerequisite tasks
  ansible.builtin.include_tasks: prerequisites_debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Alloy | prerequisites | Run RedHat/EL prerequisite tasks
  ansible.builtin.include_tasks: prerequisites_redhat.yml
  when: ansible_facts['os_family'] == 'RedHat'
