---
- name: Converge
  hosts: all
  become: true
  vars:
    alloy_loki_url: "http://127.0.0.1:3100/loki/api/v1/push"
    alloy_tenant_id: "molecule_test"
    alloy_manage_service_restart: false
  roles:
    - role: grzegorzfranus.alloy
